### ISSUE TITLE
Dark theme Implementation for new DAPP

### ISSUE THREAD

**Issue by zaryab2000** [ethereum-push-notification-service/epns-dapp#20]

**Comment by Aman035** [comment]
### **Before :** 
![image](https://user-images.githubusercontent.com/54989169/154902740-c91de08a-ec0c-4963-9776-330ca3d61ae0.png)

### **After**
![image](https://user-images.githubusercontent.com/54989169/154902434-5f76ce5f-b010-4ac8-942f-d76bec4154de.png)

The channel should not be visible behind the search bar during scrolling

**Comment by Aman035** [comment]
1. The terms & policies line is not fully visible in dark mode.
2. There is some padding issue at the bottom.
3. "Connect You Wallet" modal should also be in a dark theme.

![image](https://user-images.githubusercontent.com/54989169/154903165-5f7f2805-dff9-42d1-8ab0-c0ffc0dd41d7.png)

**Comment by Aman035** [comment]
Notification should be in dark theme (This is related to Frontend - SDK)
![image](https://user-images.githubusercontent.com/54989169/154904189-5fdd121e-c122-498b-8d78-b1118daa607b.png)

**Comment by Aman035** [comment]
Change Spam Box Modal Background to match dark theme
![image](https://user-images.githubusercontent.com/54989169/154904570-07733567-9795-420c-a189-6fdf87e094c3.png)

**Comment by Aman035** [comment]
A different dark theme pallet for support page.
![image](https://user-images.githubusercontent.com/54989169/154908215-5429f9eb-29c2-4b83-8663-1a2a1bcb1324.png)

**Comment by Aman035** [comment]
Create Channel text not visible in dark mode
![image](https://user-images.githubusercontent.com/54989169/154911189-0cf7be33-4897-4b09-b345-b52b058e5d41.png)
![image](https://user-images.githubusercontent.com/54989169/154911230-7b2f39d6-bd1e-4bb7-bd38-a96850405ac5.png)

**Comment by Aman035** [comment]
Dark Theme in Olvy (Need to see if olvy supports a dark mode)
![image](https://user-images.githubusercontent.com/54989169/154912245-bf892700-1bce-4259-8429-cae529da34e5.png)

**Comment by Aman035** [comment]
Fixed by #27
